version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prefect_server
    ports:
      - "5432:5432"
    networks:
      - tutorial_network

  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - tutorial_network

  streamlit-dash:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - tutorial_network

networks:
  tutorial_network:
    driver: bridge
