name: pydata24_prefect
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - httpx>=0.26.0
  - kafka-python-ng>=2.2.2
  - pymongo>=4.7.3
  - pandas>=2.2.0
  - numpy>=1.26.3
  - dask>=2024.5.2
  - nltk=3.8.1
  - streamlit>=1.30.0
  - wordcloud>=1.9.3
  - plotly=5.22.0
  - matplotlib>=3.8.4
  - python-dotenv>=1.0.1
  - ipykernel
  - pip:
    - prefect>=3
    - spacy>=3.7.5
    - spacytextblob>=4.0.0