name: pydata24_prefect_c
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip==24.2
  - poetry>=1.8.3
  - httpx>=0.26.0
  - kafka-python-ng>=2.2.2
  - pymongo>=4.8.0
  - pandas>=2.2.0
  - numpy>=1.26.3,<2.0
  - dask>=2024.8.1
  - nltk=3.8.1
  - streamlit>=1.37.1
  - wordcloud>=1.9.3
  - plotly=5.23.0
  - matplotlib>=3.9.2
  - python-dotenv>=1.0.1
  - pytest>=8.3.2
  - ipykernel==6.29.5
  - pip:
    - prefect==3.0.1
    - spacy>=3.7.5
    - spacytextblob>=4.0.0